name: Publish documentation

on:
  workflow_dispatch

jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - name: Set up JDK 17
          uses: actions/setup-java@v4
          with:
            java-version: '17'
            distribution: 'temurin'
        - name: Publish to GitHub Pages
          shell: bash
          run: |
            ssh-add
            git config user.name github-actions[bot]
            git config user.email github-actions[bot]@users.noreply.github.com
            ./mvnw --batch-mode --no-transfer-progress install --file pom.xml
            cd changesets-maven-plugin
            ../mvnw --batch-mode --no-transfer-progress clean site scm-publish:publish-scm
